[package]
name = "stack-overflow-detection"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
esp-hal = {  features = ["esp32c3"], git = "https://github.com/esp-rs/esp-hal.git", package = "esp-hal" }
esp-backtrace   = { version = "0.11.0", features = ["esp32c3", "panic-handler", "exception-handler", "println"] }
esp-println     = { version = "0.9.0", features = ["esp32c3", "uart"] }
critical-section = "1.1.2"
